# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# Dynamic theme – switcher will update this file
include ./kitty-themes/active.conf

allow_remote_control yes

font_family JetBrainsMono Nerd Font Mono
font_size 10.0
bold_font auto
italic_font auto
bold_italic_font auto
disable_ligatures no

background_opacity 0.8
dynamic_background_opacity 1
confirm_os_window_close 0

scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

cursor_trail 1
linux_display_server auto
scrollback_lines 2000
wheel_scroll_min_lines 1
enable_audio_bell no
window_padding_width 4

selection_foreground none
selection_background none