# ===================
# ==== AUTOSTART ====
# ===================
# Autostart necessary processes (notifications daemons, status bars, etc.)

exec-once = waybar & awww-daemon & swaync
exec-once = /usr/lib/xdg-desktop-portal -r & /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store & wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = nm-applet
exec-once = swayosd-server