# ===============
# ==== INPUT ====
# ===============

input {
    kb_layout = us,ir
    kb_variant = 
    kb_model = 
    kb_options = grp:win_space_toggle
    kb_rules = 
    
    follow_mouse = 1
    sensitivity = 0.2   # Range -1 to 1
    
    touchpad {
        natural_scroll = false
    }
}

# Per‑device configuration
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}