# ----------------------
# ---- LOOK AND FEEL ----
# ----------------------
# See https://wiki.hyprland.org/Configuring/Variables/

general {
    gaps_in = 9
    gaps_out = 18
    border_size = 1
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 14
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 10
        render_power = 4
    }

    blur {
        enabled = true
        size = 7
        passes = 3
        vibrancy = 0.1696
    }
}

animations {
    enabled = true
}

# Bezier curves
bezier = easeOutQuint, 0.23, 1, 0.32, 1
bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
bezier = linear, 0, 0, 1, 1
bezier = almostLinear, 0.5, 0.5, 0.75, 1
bezier = quick, 0.15, 0, 0.1, 1

# Springs
spring = easy, 1, 71.2633, 15.8273644

# Animations for different leaves
animation = global, 1, 10, default
animation = border, 1, 5.39, easeOutQuint


animation = windowsOut, 1, 0.6, linear, popin 87%
animation = windowsIn, 1, 0.7, linear, popin 87%

animation = fadeIn, 1, 1.73, almostLinear
animation = fadeOut, 1, 1.46, almostLinear
animation = fade, 1, 3.03, quick
animation = layers, 1, 3.81, easeOutQuint
animation = layersIn, 1, 4, easeOutQuint, fade
animation = layersOut, 1, 1.5, linear, fade
animation = fadeLayersIn, 1, 1.79, almostLinear
animation = fadeLayersOut, 1, 1.39, almostLinear
animation = workspaces, 1, 1.94, almostLinear, fade
animation = workspacesIn, 1, 1.21, almostLinear, fade
animation = workspacesOut, 1, 1.94, almostLinear, fade
animation = zoomFactor, 1, 7, quick

# Optional: Smart gaps / no gaps when only one window
# Uncomment the following lines if desired:
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
#
# windowrulev2 = bordersize 0, rounding 0, workspace w[tv1], floating:0
# windowrulev2 = bordersize 0, rounding 0, workspace f[1], floating:0

# Dwindle layout settings
dwindle {
    preserve_split = true
}

# Master layout settings
master {
    new_status = master
}

# Scrolling layout settings
scrolling {
    fullscreen_on_one_column = true
}