# ----------------------
# ----- PERMISSIONS -----
# ----------------------
# See https://wiki.hyprland.org/Configuring/Advanced-and-Cool/Permissions/
# Permission changes require a Hyprland restart and are not applied on‑the‑fly
# for security reasons.

# Uncomment the following line if you want to enforce ecosystem permissions:
# ecosystem {
#     enforce_permissions = true
# }

permission = /usr/(bin|local/bin)/grim, screencopy, allow