# --------------------------------
# ---- WINDOWS AND WORKSPACES ----
# --------------------------------
# See https://wiki.hyprland.org/Configuring/Window-Rules/
# and https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Useful Window Rules

# Ignore maximize requests from all apps (you'll probably like this)
windowrulev = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# Layer rules example (commented):
# layerrule = noanim, namespace:^my-overlay$

# Hyprland-run window rules
windowrulev = float, class:hyprland-run
windowrulev = move 20 monitor_h-120, class:hyprland-run