# Rosé Pine for Kitty
foreground #e0def4
background #191724
cursor #e0def4
color0 #191724
color1 #eb6f92
color2 #9ccfd8
color3 #f6c177
color4 #c4a7e7
color5 #ebbcba
color6 #31748f
color7 #e0def4
color8 #26233a
color9 #eb6f92
color10 #9ccfd8
color11 #f6c177
color12 #c4a7e7
color13 #ebbcba
color14 #31748f
color15 #e0def4
selection_foreground #191724
selection_background #e0def4