# ======================================
# MODULES
# ======================================
source = ~/.config/hypr/settings/autostart.conf
source = ~/.config/hypr/settings/input.conf
source = ~/.config/hypr/settings/keybinds.conf
source = ~/.config/hypr/settings/looks.conf
source = ~/.config/hypr/settings/misc.conf
source = ~/.config/hypr/settings/permissions.conf
source = ~/.config/hypr/settings/windowrules.conf


# ======================================
# MONITORS
# ======================================
monitor = , preferred, auto, 1.25

# ======================================
# ENVIRONMENT VARIABLES
# ======================================
env = HYPRCURSOR_THEME,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_SESSION_TYPE,wayland
env = GDK_BACKEND,wayland

gesture = 3, horizontal, workspace, scale: 1.5 

source = ~/.config/hypr/active-theme.conf