general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim screen after 150 seconds (2.5 minutes)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Lock screen after 90 seconds
listener {
    timeout = 90
    on-timeout = hyprlock -c ~/.config/hypr/hyprlock/hyprlock.conf
}

# Turn off screen after 120 seconds (2 minutes after locking)
listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}